# installing dependencies
echo "---- STAGE 4 ----"
# installing package
echo " "
echo "★ installing packages..."
echo " "
if sudo apt-get install libyaml-dev; then
    echo "✓ installed packages successfully"
else
    echo "✘ failed to install package / already installed "
fi
# changing dir to /var/canvas
echo " "
echo "★ changing dir..."
echo " "
cd 
cd /var/canvas
# bundler
echo " "
echo "★ installing bundler "
echo " "
if sudo gem install bundler --version 2.3.26 ; then
    echo "✓ bundler installed successfully"
else
    echo "✘ failed to install bundler"
fi
# bundle global
echo " "
echo "★ globally setting bundler"
echo " "
if bundle config set --local path vendor/bundle ; then
    echo "✓ bundler has been set globally"
else
    echo "✘ failed to globally set bundler"
fi
# installing bundle 
echo " "
echo "★ installing bundle... "
echo " "
if bundle install; then
    echo "✓ bundle installation successfull"
else
    echo "✘ bundle installaiton failed"
fi
# updating strscan
echo " "
echo "★ updating strscan... "
echo " "
if sudo gem update strscan ; then
    echo "✓ strscan has been updated successfully"
else
    echo "✘ failed to install strscan"
fi
# removing stringio
echo " "
echo "★ removing old stringio... "
echo " "
if sudo gem uninstall stringio ; then
    echo "✓ stringio has been removed"
else
    echo "✘ failed to remove stringio"
fi

# installing specific version of stringio
echo " "
echo "★ installing latest stringio... "
echo " "
if sudo gem install stringio -v 3.0.8; then
    echo "✓ stringio has been updated to latest version "
else
    echo "✘ failed to update stringio to latest version"
fi
# yarn install
echo " "
echo "★ installing yarn... "
echo " "
if yarn install; then
    echo "✓ installed successfully yarn"
else
    echo "✘ failed installing yarn"
fi

# moving database (rails file) 
echo " "
echo "★ moving rails files... "
echo " "
mv db/migrate/20210823222355_change_immersive_reader_allowed_on_to_on.rb .; 
mv db/migrate/20210812210129_add_singleton_column.rb db/migrate/20111111214311_add_singleton_column.rb
echo "✓ successfully moved rails files"

# gulping yarn
echo " "
echo "★ yarn gulp "
echo " "
if yarn gulp rev; then
    echo "✓ successfully gulped yarn "
else
    echo "✘ failed to gulp yarn"
fi

# bundling rake
echo " "
echo "★ begining initial_setup for rails "
echo " "
if RAILS_ENV=production bundle exec rake db:initial_setup; then
    echo "✓ successfully completed initial rails setup "
else
    echo "✘ failed to complete the initial rails setup"
fi
# moving files
mv 20210823222355_change_immersive_reader_allowed_on_to_on.rb db/migrate/.
echo " "
echo "★ migrating bundle "
echo " "
if RAILS_ENV=production bundle exec rake db:migrate ;  then
    echo "✓ successfully completed migrating rails setup"
else
    echo "✘ failed to complete the migrating rails setup"
fi
echo " "
echo "★ making dir "
echo " "
if mkdir -p log tmp/pids public/assets app/stylesheets/brandable_css_brands; then
    echo "✓ successfully completed making dir"
else    
    echo "✘ failed in making dir for log and assets"
fi
echo " "
echo "★ creating css dir "
echo " "
if touch app/stylesheets/_brandable_variables_defaults_autogenerated.scss Gemfile.lock log/production.log; then
    echo "✓ successfully created dir for css and brand variables"
else
    echo "✘ failed to created dir for css and brand variables"
fi
echo " "
echo "★ compiling assets "
echo " "
if RAILS_ENV=production bundle exec rake canvas:compile_assets; then 
    echo "✓ successfully compiled the assets"
else
    echo "✘ failed to compile the assets"
fi